name: TheGuide
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.2.1
  - astropy
  - matplotlib=3.10.0
  - scipy
  - pandas
  - astroquery
  - jupyter
  - ipython
  - jupyterlab
  - ipywidgets
  - ipympl=0.9.6
  - ipykernel
  - emcee
  - ipydatagrid
  - seaborn
  - corner
  - tqdm
  - requests
  - pyvo
  - pip
  - pip:
      - MulensModel
      - VBMicrolensing

